version: '3.8'

services:
  # Service principal Next.js
  structureclerk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: structureclerk-app
    restart: unless-stopped

    # Port mapping: hôte:conteneur
    ports:
      - "3000:3000"

    # Variables d'environnement
    # Remplacer avec vos vraies valeurs
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}

    # Fichier .env (optionnel, si vous utilisez un fichier .env)
    env_file:
      - .env.production

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Ressources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

    # Réseau
    networks:
      - structureclerk-network

networks:
  structureclerk-network:
    driver: bridge
